# Generated by Django 3.0.1 on 2019-12-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='Team',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='birth_date',
        ),
    ]
